logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level --- %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level --- %msg%n
logging.file.name=server.log
logging.level.org.zalando.logbook: INFO

logging.level.org.springframework.jdbc=INFO
logging.level.org.springframework.jdbc.core=INFO
logging.level.org.springframework.jdbc.support=INFO

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=create-drop
#
spring.datasource.url=jdbc:h2:file:./db/filmorate
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.mvc.log-request-details=true

# ???????? ??????? TRACE ??? DEBUG ??? ???-??????????? Spring
logging.level.org.springframework.web=TRACE