-- Создание таблиц (если не существуют)
CREATE TABLE IF NOT EXISTS "User"
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR,
    email    VARCHAR,
    login    VARCHAR,
    birthday DATE
);

CREATE TABLE IF NOT EXISTS MPA
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE IF NOT EXISTS Film
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR,
    description  VARCHAR,
    duration     INTEGER,
    release_date DATE,
    mpa_id       INTEGER,
    FOREIGN KEY (mpa_id) REFERENCES MPA (id)
);

CREATE TABLE IF NOT EXISTS Likes
(
    user_id INTEGER,
    film_id INTEGER,
    PRIMARY KEY (user_id, film_id),
    FOREIGN KEY (user_id) REFERENCES "User" (id),
    FOREIGN KEY (film_id) REFERENCES Film (id)
);

CREATE TABLE IF NOT EXISTS Friend_Status
(
    status_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_type BOOLEAN
);

CREATE TABLE IF NOT EXISTS Friends
(
    user_id          INTEGER,
    friend_id        INTEGER,
    friend_status_id INTEGER DEFAULT 1,
    PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id) REFERENCES "User" (id),
    FOREIGN KEY (friend_id) REFERENCES "User" (id),
    FOREIGN KEY (friend_status_id) REFERENCES Friend_Status (status_id)
);

CREATE TABLE IF NOT EXISTS Genres
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE IF NOT EXISTS Film_Genre
(
    film_id  INTEGER,
    genre_id INTEGER,
    PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id) REFERENCES Film (id),
    FOREIGN KEY (genre_id) REFERENCES Genres (id)
);